<a href="https://colab.research.google.com/github/ChoeTaeBin/deep_learning_study/blob/master/Tensor_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import torch

pytorch의 기본 자료형은 Tensor이다.

In [2]:
a = torch.tensor([1,2,3])
print(a, type(a))

tensor([1, 2, 3]) <class 'torch.Tensor'>


Tensor 인스턴스를 생성하는 다양한 방법

In [3]:
b = torch.tensor([[1, 2],
                  [3, 4]])
print(b)

tensor([[1, 2],
        [3, 4]])


In [5]:
c = torch.tensor([[1, 2],
                  [3, 4]], dtype = torch.float64)
print(c)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [6]:
d = torch.arange(0, 10)
print(d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
e = torch.zeros(2, 3)
print(e)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
f = torch.rand(2, 3)
print(f)

tensor([[0.5725, 0.1636, 0.7370],
        [0.4240, 0.4729, 0.0772]])


Tensor.size()

In [10]:
print(f.size())

torch.Size([2, 3])


torch.linspace()

In [12]:
g = torch.linspace(-5, 5, 10)
print(g)

tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])


numpy 배열과 상호 변환

In [15]:
a = torch.tensor([[1, 2],
                  [3, 4.]])#모두 실수 타입으로 만들기 위해서 마지막 4 옆에 .을 찍어줌

b = a.numpy() #Tensor -> numpy배열
print(b, type(b))

[[1. 2.]
 [3. 4.]] <class 'numpy.ndarray'>


In [16]:
c = torch.from_numpy(b) #numpy배열 -> Tensor
print(c, type(c))

tensor([[1., 2.],
        [3., 4.]]) <class 'torch.Tensor'>


numpy 배열처럼 indexing, slicing 가능

In [17]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [18]:
print(a[0, 1]) #0행 1열 출력

tensor(2)


In [19]:
print(a[1:2, :2]) #슬라이싱 이용

tensor([[4, 5]])


In [20]:
print(a[: , [0, 2]]) #리스트 이용

tensor([[1, 3],
        [4, 6]])


In [21]:
print(a[a>2]) #조건식 이용

tensor([3, 4, 5, 6])


In [23]:
#같은 방식으로 변경도 가능

a[ : , : ] = 1
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [25]:
a[a==1] = 0
print(a)

tensor([[0, 0, 0],
        [0, 0, 0]])


Tensor 연산

In [26]:
#vector
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

#matrix
C = torch.tensor([[6, 5, 4],
                  [3, 2, 1]])

In [27]:
print(a+3)

tensor([4, 5, 6])


In [28]:
print(a + b)

tensor([5, 7, 9])


In [29]:
print(C + 2)

tensor([[8, 7, 6],
        [5, 4, 3]])


In [30]:
print(C + a)

tensor([[7, 7, 7],
        [4, 4, 4]])


In [31]:
print(C + C)

tensor([[12, 10,  8],
        [ 6,  4,  2]])


In [51]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([1, 2, 3])
c = torch.tensor([[1],
                  [2],
                  [3]])

In [52]:
d = a%b
print(d)

tensor([[0, 0, 0],
        [0, 1, 0]])


In [55]:
e = a*b #성분끼리 곱
print(e)

tensor([[ 1,  4,  9],
        [ 4, 10, 18]])


In [56]:
f = a @ c #행렬곱
print(f)

tensor([[14],
        [32]])


Tensor 형태 변환

In [33]:
a = torch.arange(0, 8, 1)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [36]:
b = a.view(2, 4)
print(b)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [37]:
c = a.view(4, -1)
print(c)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])


In [38]:
d = c.view(-1) #1차원으로 펴기
print(d)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


Tensor.squeeze()  
*요소 수가 1인 차원을 삭제한다.*

In [42]:
e = d.view(1,d.size()[0])
print(e, e.size())

tensor([[0, 1, 2, 3, 4, 5, 6, 7]]) torch.Size([1, 8])


In [43]:
f = e.squeeze()
print(f, f.size())

tensor([0, 1, 2, 3, 4, 5, 6, 7]) torch.Size([8])


Tensor.unsqueeze()

In [46]:
g = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(g, g.size())

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) torch.Size([2, 4])


In [48]:
h = g.unsqueeze(2) #2차원에 1을 추가 즉, (2,4) -> (2, 4, 1)
print(h, h.size())

tensor([[[1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8]]]) torch.Size([2, 4, 1])


집계 함수

In [63]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6.]])

In [66]:
m = a.mean()
print(m, m.item())

tensor(3.5000) 3.5


In [67]:
torch.mean(a)

tensor(3.5000)

In [68]:
torch.sum(a), torch.max(a), torch.min(a), torch.var(a), torch.std(a)

(tensor(21.), tensor(6.), tensor(1.), tensor(3.5000), tensor(1.8708))